# config.yaml
detectors:
  - name: HogTokenDetector
    keywords:
      - hog
    regex:
      token: '[^A-Za-z0-9+\/]{0,1}([A-Za-z0-9+\/]{40})[^A-Za-z0-9+\/]{0,1}'
    verify:
      - endpoint: http://localhost:8000/
        # 'unsafe' must be set to true if the endpoint uses HTTP
        unsafe: true
        headers:
          - "Authorization: super secret authorization header"