name: DAST

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout git repository"
        uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: HRKU-90822da0-9ae8-4371-b444-35d905682e91
          heroku_app_name: "secdevops3"
          heroku_email: "mboeynaems@outlook.com"
      - name: DAST OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: https://secdevops3-d494818783ee.herokuapp.com/