name: TruffleHog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout git repository"
        uses: actions/checkout@v3
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown